<?php

/**
 * Implementation of hook_block_info
 */
function campaign_monitor_subscribe_block_info() {

	$blocks['campaign_monitor_subscribe'] = array(
	  'info' => t('Subscribe for newsletter block'),
	);

	return $blocks;

}


/**
 * Implementation of hook_block_view
 */
function campaign_monitor_subscribe_block_view($delta = '') {
 
  $block = array();

  if ($delta == 'campaign_monitor_subscribe') {
    $block['subject'] = t('Op de hoogte blijven?');
//    $block['content'] = array();    
    $block['content'] = _campaign_monitor_subscribe_render_block();
  }
  
  return $block;
}


/**
 * Implementation of hook_menu
 */
function campaign_monitor_subscribe_menu() {
  $items = array();
  
  $items['admin/config/campaignmonitor'] = array(
    'title' => 'Campaign Monitor settings',
	'description' => 'API settings for integration with Campaign Monitor',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('campaign_monitor_subscribe_settings'),
	'access arguments' => array('administer site configuration'),
	'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}



/**
 * Helper function to generate block
 */
function _campaign_monitor_subscribe_render_block() {

  $output = "<div class='label'>Schrijf je in voor onze nieuwsbrief en blijf op de hoogte!</div>";
  $form = drupal_get_form('campaign_monitor_subscribe');
  $output .= render($form);
	return $output;

}

/**
 * Generate subscription form
 */
function campaign_monitor_subscribe($form_state) {
	$form = array();

  $form['email'] = array(
		'#type' => 'textfield',
		'#title' => '',
		'#size' => 60,
		'#attributes' => array('placeholder' => t('je e-mailadres')),
  );	
  
  $form['captcha'] = array(
    '#type' => 'hidden',
    '#value' => '',
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
	'#value' => t('Subscribe'),
  );
  
  return $form;
}

/**
 * Submit function for subscription form
 */
function campaign_monitor_subscribe_submit($form, &$form_state) {

  $captcha = $form_state['values']['captcha'];
  if ($captcha) {
    form_set_error('email', t('Seems that you are a spammer.'));
  } else {
	  $api_key                = variable_get('campaignmonitor_api_key', '');
	  $api_client_id          = variable_get('campaignmonitor_api_client_id', '');
	  $api_subscriber_list_id = variable_get('campaignmonitor_api_subscriber_list_id', '');
	
	  include_once(drupal_get_path('module', 'campaign_monitor_subscribe') . '/lib/csrest_subscribers.php');
	  
	  $campaign_monitor = new CS_REST_Subscribers($api_subscriber_list_id, $api_key);
	  
	  $subscriber = array(
	    'EmailAddress' => $form_state['values']['email'],
		'Name' => '',
		'CustomFields' => array(),
		'Resubscribe' => TRUE,
	  );
	  
	  $result = $campaign_monitor->add($subscriber);
	
	  if ($result->http_status_code == '201') {
	    drupal_set_message(t('Email address successfully added.'));
	  } else {
		form_set_error('email', t('Could not subscribe email address. Please try again.')); 
	  }
  }  
}

/**
 * Validation function for subscription form
 */
function campaign_monitor_subscribe_validate($form, &$form_state) {
  $email = $form_state['values']['email'];
  
  if (!valid_email_address($email)) {
	form_set_error('', t('Please enter a valid email address.'));  
  }
}

/**
 * Generate admin/settings form
 */
function campaign_monitor_subscribe_settings($form_state) {
  $form['settings'] = array(
    '#type' => 'fieldset',
	'#title' => t('Settings'),
  );	
  
  $form['settings']['api_key'] = array(
    '#type' => 'textfield',
	'#title' => t('API Key'),
	'#default_value' => variable_get('campaignmonitor_api_key', ''),
	'#size' => 60,
  );
  
  $form['settings']['api_client_id'] = array(
    '#type' => 'textfield',
	'#title' => t('API Client Id'),
	'#default_value' => variable_get('campaignmonitor_api_client_id', ''),
	'#size' => 60,
  );
  
  $form['settings']['api_subscriber_list_id'] = array(
    '#type' => 'textfield',
	'#title' => t('API Subscriber List Id'),
	'#default_value' => variable_get('campaignmonitor_api_subscriber_list_id', ''),
  );
    
  $form['submit'] = array(
    '#type' => 'submit',
	'#value' => 'Save',
  );
  
  return $form;
}

/**
 * Submit function for settings form
 */
function campaign_monitor_subscribe_settings_submit($form, &$form_state) {
  $api_key                = $form_state['values']['api_key'];
  $api_client_id          = $form_state['values']['api_client_id'];
  $api_subscriber_list_id = $form_state['values']['api_subscriber_list_id'];
  
  variable_set('campaignmonitor_api_key', $api_key);
  variable_set('campaignmonitor_api_client_id', $api_client_id);
  variable_set('campaignmonitor_api_subscriber_list_id', $api_subscriber_list_id);
  
  drupal_set_message(t('Settings saved'));
}